* Exporting Agenda to iCal !!!
  [2018-03-02 Fri] [[info:org#iCalendar%20export][info:org#iCalendar export]]

     Since a single Org entry can result in multiple iCalendar entries—as
  timestamp, deadline, scheduled item, or TODO item—Org adds prefixes to
  the UID, depending on which part of the Org entry triggered the creation
  of the iCalendar entry.  Prefixing ensures UIDs remains unique, yet
  enable synchronization programs trace the connections.

  ‘C-c C-e c f     (org-icalendar-export-to-ics)’
       Create iCalendar entries from the current Org buffer and store them
       in the same directory, using a file extension ‘.ics’.
  ‘C-c C-e c a     (org-icalendar-export-agenda-files)’
       Create iCalendar entries from Org files in ‘org-agenda-files’ and
       store in a separate iCalendar file for each Org file.
  ‘C-c C-e c c     (org-icalendar-combine-agenda-files)’
       Create a combined iCalendar file from Org files in
       ‘org-agenda-files’ and write it to
       ‘org-icalendar-combined-agenda-file’ file name.
