(deftheme toby
  "Created 2015-05-13.")

(custom-theme-set-variables
 'toby
 '(ansi-color-names-vector [solarized-bg red green yellow blue magenta cyan solarized-fg])
 '(aquamacs-additional-fontsets nil)
 '(aquamacs-customization-version-id 211)
 '(aquamacs-tool-bar-user-customization nil)
 '(compilation-always-kill t)
 '(compilation-ask-about-save nil)
 '(compilation-auto-jump-to-first-error nil)
 '(compilation-scroll-output nil)
 '(default-frame-alist (quote ((vertical-scroll-bars) (cursor-type . box) (internal-border-width . 0) (left-fringe . 1) (right-fringe) (fringe) (background-color . "#211E1E") (background-mode . dark) (background-toolbar-color . "#cf3ccf3ccf3c") (border-color . "Grey") (bottom-toolbar-shadow-color . "#79e77df779e7") (cursor-color . "#FFFFFF") (foreground-color . "#DADADA") (mouse-color . "Grey") (top-toolbar-shadow-color . "#fffffbeeffff") (viper-saved-cursor-color-in-replace-mode . "Red3"))))
 '(dired-auto-revert-buffer (quote dired-directory-changed-p))
 '(ediff-window-setup-function (quote ediff-setup-windows-plain))
 '(erc-modules (quote (autojoin button completion fill irccontrols list match menu move-to-prompt netsplit networks noncommands readonly ring scrolltobottom smiley stamp spelling track)))
 '(erc-server "irc.freenode.net")
 '(global-toby-mode t)
 '(js-expr-indent-offset 2)
 '(js-indent-level 2)
 '(magit-process-popup-time 20)
 '(ns-tool-bar-display-mode nil)
 '(ns-tool-bar-size-mode nil)
 '(org-agenda-files (quote ("~/Dropbox/org/ib-tasks.org" "~/Dropbox/org/my-tasks.org")))
 '(revert-without-query (quote (".*")))
 '(rspec-rake-command "bundle exec rake")
 '(rspec-spec-command " rspec ")
 '(rspec-use-bundler-when-possible nil)
 '(rspec-use-rake-flag nil)
 '(rspec-use-rake-when-possible nil)
 '(rspec-use-rvm nil)
 '(ruby-deep-arglist nil)
 '(ruby-deep-indent-paren nil)
 '(ruby-use-encoding-map t)
 '(safe-local-variable-values (quote ((encoding . utf-8) (whitespace-line-column . 80) (lexical-binding . t))))
 '(sml/pos-id-separator (quote ("" (:propertize " " face powerline-active1) (:eval (propertize " " (quote display) (funcall (intern (format "powerline-%s-%s" powerline-default-separator (car powerline-default-separator-dir))) (quote powerline-active1) (quote powerline-active2)))) (:propertize " " face powerline-active2))))
 '(sml/pos-minor-modes-separator (quote ("" (:propertize " " face powerline-active1) (:eval (propertize " " (quote display) (funcall (intern (format "powerline-%s-%s" powerline-default-separator (cdr powerline-default-separator-dir))) (quote powerline-active1) nil))) (:propertize " " face sml/global))))
 '(sml/pre-id-separator (quote ("" (:propertize " " face sml/global) (:eval (propertize " " (quote display) (funcall (intern (format "powerline-%s-%s" powerline-default-separator (car powerline-default-separator-dir))) nil (quote powerline-active1)))) (:propertize " " face powerline-active1))))
 '(sml/pre-minor-modes-separator (quote ("" (:propertize " " face powerline-active2) (:eval (propertize " " (quote display) (funcall (intern (format "powerline-%s-%s" powerline-default-separator (cdr powerline-default-separator-dir))) (quote powerline-active2) (quote powerline-active1)))) (:propertize " " face powerline-active1))))
 '(sml/pre-modes-separator #(" " 0 1 (face sml/modes)))
 '(visual-line-mode nil)
 '(warning-minimum-level :error)
 '(whitespace-style (quote (trailing tab-mark)))
 '(column-number-mode t)
 '(electric-pair-mode t)
 '(global-auto-revert-mode t)
 '(global-linum-mode t)
 '(menu-bar-mode nil)
 '(custom-safe-themes (quote ("26614652a4b3515b4bbbb9828d71e206cc249b67c9142c06239ed3418eff95e2" "ee2aa6bcaabf4b9f7446dc56bc6ce1f1292885cfaf578de00e309b520a45cdaa" default)))
 '(eval-sexp-fu-flash-mode nil)
 '(winner-mode t))

(custom-theme-set-faces
 'toby
 '(highlight ((t (:background "#073642"))))
 '(hl-line ((t (:background "#002b36"))))
 '(idle-highlight ((t (:foreground "khaki"))))
 '(magit-item-highlight ((t (:inherit highlight))))
 '(rainbow-delimiters-depth-1-face ((((class color) (min-colors 89)) (:foreground "#2aa198"))))
 '(term-color-blue ((t (:background "blue2" :foreground "deep sky blue"))))
 '(cursor ((((class color) (min-colors 89)) (:foreground "#002b36" :background "#839496" :inverse-video t))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((t (:family "Sans Serif"))))
 '(escape-glyph ((t (:foreground "goldenrod4"))))
 '(minibuffer-prompt ((t (:background "#211E1E" :foreground "#93a1a1" :box nil))))
 '(region ((((class color) (min-colors 89)) (:foreground "#002b36" :background "#93a1a1"))))
 '(shadow ((((class color grayscale) (min-colors 88) (background light)) (:foreground "grey50")) (((class color grayscale) (min-colors 88) (background dark)) (:foreground "grey70")) (((class color) (min-colors 8) (background light)) (:foreground "green")) (((class color) (min-colors 8) (background dark)) (:foreground "yellow"))))
 '(secondary-selection ((((class color) (min-colors 89)) (:background "#002b36"))))
 '(trailing-whitespace ((((class color) (min-colors 89)) (:background "#dc322f"))))
 '(font-lock-builtin-face ((((class color) (min-colors 89)) (:foreground "#268bd2" :slant italic))))
 '(font-lock-comment-delimiter-face ((((class color) (min-colors 89)) (:foreground "#586e75"))))
 '(font-lock-comment-face ((t (:foreground "#586e75"))))
 '(font-lock-constant-face ((((class color) (min-colors 89)) (:foreground "#268bd2" :weight bold))))
 '(font-lock-doc-face ((((class color) (min-colors 89)) (:foreground "#2aa198" :slant italic))))
 '(font-lock-function-name-face ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(font-lock-keyword-face ((((class color) (min-colors 89)) (:foreground "#859900" :weight bold))))
 '(font-lock-negation-char-face ((((class color) (min-colors 89)) (:foreground "#839496"))))
 '(font-lock-preprocessor-face ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(font-lock-regexp-grouping-backslash ((t (:inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:inherit (bold)))))
 '(font-lock-string-face ((((class color) (min-colors 89)) (:foreground "#2aa198"))))
 '(font-lock-type-face ((((class color) (min-colors 89)) (:foreground "#b58900"))))
 '(font-lock-variable-name-face ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(font-lock-warning-face ((((class color) (min-colors 89)) (:foreground "#dc322f" :weight bold :underline t))))
 '(button ((t (:underline t))))
 '(link ((((class color) (min-colors 89)) (:foreground "#b58900" :underline t :weight bold))))
 '(link-visited ((((class color) (min-colors 89)) (:foreground "#b58900" :underline t :weight normal))))
 '(fringe ((((class color) (min-colors 89)) (:foreground "#839496" :background "#073642"))))
 '(header-line ((((class color) (min-colors 89)) (:foreground "#b58900" :background "#073642" :box (:line-width -1 :style released-button)))))
 '(tooltip ((((class color) (min-colors 89)) (:background "#7B6000" :foreground "#DEB542" :inherit variable-pitch))))
 '(mode-line ((((class color) (min-colors 89)) (:box (:line-width -1 :style released-button) :background "#000000" :foreground "#839496"))))
 '(mode-line-buffer-id ((((class color) (min-colors 89)) (:foreground "#93a1a1" :weight bold))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((((class color) (min-colors 88)) (:box (:line-width 2 :color "grey40" :style released-button))) (t (:inherit (highlight)))))
 '(mode-line-inactive ((((class color) (min-colors 89)) (:foreground "#839496" :background "#7f7f7f" :box (:line-width -1 :style released-button)))))
 '(isearch ((((class color) (min-colors 89)) (:foreground "#b58900" :background "#073642"))))
 '(isearch-fail ((((class color) (min-colors 89)) (:foreground "#839496" :background "#dc322f"))))
 '(lazy-highlight ((((class color) (min-colors 89)) (:foreground "#b58900" :background "#073642"))))
 '(match ((((class color) (min-colors 89)) (:background "#073642" :foreground "#93a1a1" :weight bold))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch)))))
 '(compilation-info ((((class color) (min-colors 89)) (:foreground "#859900" :underline t))))
 '(compilation-line-number ((((class color) (min-colors 89)) (:foreground "#b58900"))))
 '(menu ((((class color) (min-colors 89)) (:foreground "#839496" :background "#002b36"))))
 '(vertical-border ((((class color) (min-colors 89)) (:foreground "#839496"))))
 '(c-annotation-face ((((class color) (min-colors 89)) (:inherit font-lock-constant-face))))
 '(custom-variable-tag ((((class color) (min-colors 89)) (:foreground "#2aa198"))))
 '(custom-comment-tag ((((class color) (min-colors 89)) (:foreground "#586e75"))))
 '(custom-group-tag ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(custom-state ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(diff-added ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(diff-changed ((((class color) (min-colors 89)) (:foreground "#b58900"))))
 '(diff-removed ((((class color) (min-colors 89)) (:foreground "#dc322f"))))
 '(diff-header ((((class color) (min-colors 89)) (:background "#002b36"))))
 '(diff-file-header ((((class color) (min-colors 89)) (:background "#002b36" :foreground "#839496" :bold t))))
 '(eshell-prompt ((((class color) (min-colors 89)) (:foreground "#b58900" :weight bold))))
 '(eshell-ls-archive ((((class color) (min-colors 89)) (:foreground "#dc322f" :weight bold))))
 '(eshell-ls-directory ((((class color) (min-colors 89)) (:foreground "#268bd2" :weight bold))))
 '(eshell-ls-executable ((((class color) (min-colors 89)) (:foreground "#dc322f" :weight bold))))
 '(eshell-ls-unreadable ((((class color) (min-colors 89)) (:foreground "#839496"))))
 '(eshell-ls-special ((((class color) (min-colors 89)) (:foreground "#b58900" :weight bold))))
 '(eshell-ls-symlink ((((class color) (min-colors 89)) (:foreground "#2aa198" :weight bold))))
 '(flyspell-duplicate ((((class color) (min-colors 89)) (:foreground "#b58900" :weight bold :underline t))))
 '(flyspell-incorrect ((((class color) (min-colors 89)) (:foreground "#dc322f" :weight bold :underline t))))
 '(hi-yellow ((((class color) (min-colors 89)) (:foreground "#7B6000" :background "#DEB542"))))
 '(hi-pink ((((class color) (min-colors 89)) (:foreground "#93115C" :background "#F771AC"))))
 '(hi-green ((((class color) (min-colors 89)) (:foreground "#546E00" :background "#B4C342"))))
 '(hi-blue ((((class color) (min-colors 89)) (:foreground "#00629D" :background "#69B7F0"))))
 '(hi-black-b ((((class color) (min-colors 89)) (:foreground "#93a1a1" :background "#002b36" :weight bold))))
 '(hi-blue-b ((((class color) (min-colors 89)) (:foreground "#00629D" :weight bold))))
 '(hi-green-b ((((class color) (min-colors 89)) (:foreground "#546E00" :weight bold))))
 '(hi-red-b ((((class color) (min-colors 89)) (:foreground "#dc322f" :weight bold))))
 '(hi-black-hb ((((class color) (min-colors 89)) (:foreground "#93a1a1" :background "#002b36" :weight bold))))
 '(ido-first-match ((((class color) (min-colors 89)) (:foreground "#b58900" :weight bold))))
 '(ido-only-match ((((class color) (min-colors 89)) (:foreground "#cb4b16" :weight bold))))
 '(ido-subdir ((((class color) (min-colors 89)) (:foreground "#b58900"))))
 '(linum ((((class color) (min-colors 89)) (:foreground "#839496" :background "black"))))
 '(magit-section-title ((((class color) (min-colors 89)) (:foreground "#b58900" :weight bold))))
 '(magit-branch ((((class color) (min-colors 89)) (:foreground "#cb4b16" :weight bold))))
 '(message-header-name ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(message-header-other ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(message-header-to ((((class color) (min-colors 89)) (:foreground "#b58900" :weight bold))))
 '(message-header-cc ((((class color) (min-colors 89)) (:foreground "#b58900" :weight bold))))
 '(message-header-newsgroups ((((class color) (min-colors 89)) (:foreground "#b58900" :weight bold))))
 '(message-header-subject ((((class color) (min-colors 89)) (:foreground "#cb4b16" :weight bold))))
 '(message-header-xheader ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(message-mml ((((class color) (min-colors 89)) (:foreground "#b58900" :weight bold))))
 '(org-agenda-date ((((class color) (min-colors 89)) (:foreground "#839496" :background "#073642" :weight bold :box (:line-width 4 :color "#073642")))))
 '(org-agenda-date-weekend ((((class color) (min-colors 89)) (:inherit org-agenda-date :slant italic))))
 '(org-agenda-date-today ((((class color) (min-colors 89)) (:inherit org-agenda-date :slant italic underline: t))))
 '(org-agenda-done ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(org-archived ((((class color) (min-colors 89)) (:foreground "#586e75" :weight normal))))
 '(org-block ((((class color) (min-colors 89)) (:foreground "#586e75"))))
 '(org-block-begin-line ((t (:foreground "#586e75" :slant italic))))
 '(org-checkbox ((((class color) (min-colors 89)) (:background "#002b36" :foreground "#839496" :box (:line-width 1 :style released-button)))))
 '(org-code ((((class color) (min-colors 89)) (:foreground "#586e75"))))
 '(org-date ((((class color) (min-colors 89)) (:foreground "#268bd2" :underline t))))
 '(org-done ((((class color) (min-colors 89)) (:bold t :weight bold :foreground "#859900"))))
 '(org-ellipsis ((((class color) (min-colors 89)) (:foreground "#586e75"))))
 '(org-formula ((((class color) (min-colors 89)) (:foreground "#b58900"))))
 '(org-headline-done ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(org-hide ((((class color) (min-colors 89)) (:foreground "#002b36"))))
 '(org-level-1 ((((class color) (min-colors 89)) (:foreground "#cb4b16"))))
 '(org-level-2 ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(org-level-3 ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(org-level-4 ((((class color) (min-colors 89)) (:foreground "#b58900"))))
 '(org-level-5 ((((class color) (min-colors 89)) (:foreground "#2aa198"))))
 '(org-level-6 ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(org-level-7 ((((class color) (min-colors 89)) (:foreground "#dc322f"))))
 '(org-level-8 ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(org-link ((((class color) (min-colors 89)) (:foreground "#b58900" :underline t))))
 '(org-sexp-date ((((class color) (min-colors 89)) (:foreground "#6c71c4"))))
 '(org-scheduled ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(org-scheduled-previously ((((class color) (min-colors 89)) (:foreground "#cb4b16"))))
 '(org-scheduled-today ((((class color) (min-colors 89)) (:bold t :foreground "#268bd2" :weight bold))))
 '(org-special-keyword ((((class color) (min-colors 89)) (:foreground "#586e75" :weigth bold :bold t))))
 '(org-table ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(org-tag ((((class color) (min-colors 89)) (:bold t :weight bold))))
 '(org-time-grid ((((class color) (min-colors 89)) (:foreground "#2aa198"))))
 '(org-todo ((((class color) (min-colors 89)) (:bold t :foreground "#dc322f" :weight bold))))
 '(org-upcoming-deadline ((((class color) (min-colors 89)) (:bold t :foreground "#b58900"))))
 '(org-warning ((((class color) (min-colors 89)) (:bold t :foreground "#cb4b16" :weight bold :underline t))))
 '(outline-8 ((((class color) (min-colors 89)) (:inherit default))))
 '(outline-7 ((((class color) (min-colors 89)) (:inherit outline-8 :height 1.0))))
 '(outline-6 ((((class color) (min-colors 89)) (:inherit outline-7 :height 1.0))))
 '(outline-5 ((((class color) (min-colors 89)) (:inherit outline-6 :height 1.0))))
 '(outline-4 ((((class color) (min-colors 89)) (:inherit outline-5 :height 1.0))))
 '(outline-3 ((((class color) (min-colors 89)) (:inherit outline-4 :height 1.0))))
 '(outline-2 ((((class color) (min-colors 89)) (:inherit outline-3 :height 1.0))))
 '(outline-1 ((((class color) (min-colors 89)) (:inherit outline-2 :height 1.0))))
 '(rainbow-delimiters-depth-2-face ((((class color) (min-colors 89)) (:foreground "#b58900"))))
 '(rainbow-delimiters-depth-3-face ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(rainbow-delimiters-depth-4-face ((((class color) (min-colors 89)) (:foreground "#dc322f"))))
 '(rainbow-delimiters-depth-5-face ((((class color) (min-colors 89)) (:foreground "#cb4b16"))))
 '(rainbow-delimiters-depth-6-face ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(rainbow-delimiters-depth-7-face ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(rainbow-delimiters-depth-8-face ((((class color) (min-colors 89)) (:foreground "#dc322f"))))
 '(rainbow-delimiters-depth-9-face ((((class color) (min-colors 89)) (:foreground "#b58900"))))
 '(rainbow-delimiters-unmatched-face ((((class color) (min-colors 89)) (:foreground "#839496" :background "#002b36" :inverse-video t))))
 '(sh-quoted-exec ((((class color) (min-colors 89)) (:foreground "#6c71c4" :weigth bold :bold t))))
 '(sh-escaped-newline ((((class color) (min-colors 89)) (:foreground "#b58900" :weigth bold :bold t))))
 '(sh-heredoc ((((class color) (min-colors 89)) (:foreground "#b58900" :weigth bold :bold t))))
 '(show-paren-match ((((class color) (min-colors 89)) (:foreground "#2aa198" :background "#002b36" :weight normal :inverse-video t))))
 '(show-paren-mismatch ((((class color) (min-colors 89)) (:foreground "#dc322f" :background "#002b36" :weight normal :inverse-video t))))
 '(whitespace-space ((((class color) (min-colors 89)) (:background "#002b36" :foreground "#7B6000" :inverse-video t))))
 '(whitespace-hspace ((((class color) (min-colors 89)) (:background "#002b36" :foreground "#990A1B" :inverse-video t))))
 '(whitespace-tab ((((class color) (min-colors 89)) (:background "#002b36" :foreground "#8B2C02" :inverse-video t))))
 '(whitespace-newline ((((class color) (min-colors 89)) (:foreground "#586e75"))))
 '(whitespace-trailing ((((class color) (min-colors 89)) (:foreground "#00629D" :background "#002b36" :inverse-video t))))
 '(whitespace-line ((((class color) (min-colors 89)) (:background "#002b36" :foreground "#d33682" :inverse-video nil))))
 '(whitespace-space-before-tab ((((class color) (min-colors 89)) (:background "#002b36" :foreground "#546E00" :inverse-video t))))
 '(whitespace-indentation ((((class color) (min-colors 89)) (:background "#002b36" :foreground "#93115C" :inverse-video t))))
 '(whitespace-empty ((((class color) (min-colors 89)) (:background "#839496" :foreground "#990A1B" :inverse-video t))))
 '(whitespace-space-after-tab ((((class color) (min-colors 89)) (:background "#002b36" :foreground "#3F4D91" :inverse-video t))))
 '(org-block-background ((t nil)))
 '(org-block-end-line ((t (:inherit (org-meta-line)))))
 '(comint-highlight-prompt ((t (:inherit minibuffer-prompt))))
 '(column-marker-1 ((t (:background "firebrick"))))
 '(default ((t (:background "#211E1E" :foreground "#DADADA")))))

(provide-theme 'toby)
